reverted the bindings check since this wasn't showing a diff

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -68,6 +68,8 @@ jobs:
       - uses: actions/checkout@v7
         with:
           submodules: true
+      - name: Move committed bindings aside
+        run: mv lore-sys/src/bindings.rs committed-bindings.rs
       - name: Generate bindings
         run: cargo run --manifest-path generator/Cargo.toml
       - name: Upload bindings
@@ -77,7 +79,8 @@ jobs:
           path: lore-sys/src/bindings.rs
       - name: Diff generated Rust code
         shell: bash
-        run: test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with 'cargo run --manifest-path generator/Cargo.toml'!"; git status; false)
+        run: |
+          diff -u committed-bindings.rs lore-sys/src/bindings.rs || (echo "::error::Generated bindings are different, please regenerate with 'cargo run --manifest-path generator/Cargo.toml'!"; false)
 
   test:
     name: Test on ${{ matrix.os }}
