🖊️Push and pull requests now check if the bindings are up to date.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,3 +26,24 @@ jobs:
       - uses: dtolnay/rust-toolchain@1.74.0
       - name: Cargo check
         run: cargo check --workspace --all-targets
+
+  generate-bindings:
+    name: Generate bindings
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v7
+        with:
+          submodules: true
+      - name: Clean bindings
+        run: rm lore-sys/src/bindings.rs
+      - name: Generate bindings
+        run: cargo run --manifest-path generator/Cargo.toml
+      - name: Upload bindings
+        uses: actions/upload-artifact@v7
+        with:
+          name: bindings
+          path: lore-sys/src/bindings.rs
+      - name: Diff generated Rust code
+        shell: bash
+        run: |
+          test -z "$(git status --porcelain)" || (echo "::error::Generated bindings are different, please regenerate with 'cargo run --manifest-path generator/Cargo.toml'!"; git status; false)
